# Generated by Django 4.2.3 on 2023-07-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frox_world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(default='Privilege', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('expiration', models.DateTimeField()),
                ('privilege_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frox_world.privilegetype')),
            ],
        ),
    ]
