# Generated by Django 4.2.3 on 2023-07-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frox_world', '0003_profile_purchase_server_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='server',
            name='max_online',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='server',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
